
fos_rest:
    format_listener:
            rules:
                - {path: "^/", priorities: ["json"], fallback_format: json}
    body_listener: true
    #Configurando exception y error handling en routes
    exception:
            enabled: true
    param_fetcher_listener: true
    view:
        view_response_listener: "force"
        formats:
            json: true